language: python

python:
  - "3.6"

install:
  # Setup
  - pip install enaml lxml motor markdown pygments
  
  # Testing
  - pip install pytest pytest-coverage pytest-asyncio faker jinja2
  
  # Install
  - python setup.py develop

script:
  - pytest -v tests --cov web --cov-report xml

after_success:
  - codecov
