dist: xenial
language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  # Setup
  - pip install enaml lxml markdown pygments nbconvert

  # Testing
  - pip install codecov pytest pytest-coverage pytest-benchmark faker jinja2 requests

  # Install
  - python setup.py develop

script:
  - pytest -v tests --cov web --cov-report xml

after_success:
  - codecov
