language: python

python:
  - "3.6"

services:
  - mongodb

install:
  # Setup
  - pip install enaml lxml motor markdown pygments
  
  # Testing
  - pip install codecov pytest pytest-coverage pytest-asyncio pytest-benchmark faker jinja2
  
  # Install
  - python setup.py develop

script:
  - pytest -v tests --cov web --cov-report xml

after_success:
  - codecov
