dist: xenial
language: python

python:
  - "3.6"
  - "3.7"
  
services:
  - mongodb
  
before_install:
  # Install wrk
  - sudo apt update
  - sudo apt install build-essential libssl-dev git -y
  - git clone https://github.com/wg/wrk.git wrk
  - cd wrk
  - sudo make
  - sudo cp wrk /usr/local/bin
  - cd ../

install:
  # Setup
  - pip install enaml lxml motor markdown pygments nbconvert
  
  # Testing
  - pip install codecov pytest pytest-coverage pytest-asyncio pytest-benchmark faker jinja2 requests
  
  # Install
  - python setup.py develop

script:
  - pytest -v tests --cov web --cov-report xml

after_success:
  - codecov
