dist: xenial
language: python

python:
  - "3.6"
  - "3.7"
  
services:
  - mongodb
  - mysql

install:
  # Setup
  - pip install enaml lxml motor markdown pygments nbconvert sqlalchemy aiomysql
  
  # Testing
  - pip install codecov pytest pytest-coverage pytest-asyncio pytest-benchmark faker jinja2 requests
  
  # Install
  - python setup.py develop

script:
  - pytest -v tests --cov web --cov-report xml

after_success:
  - codecov
