language: python

python:
  - "3.6"

install:
  # Setup
  - pip install enaml lxml motor markdown pygments faker jinja2
  
  # Testing
  - pip install pytest pytest-coverage pytest-asyncio

script:
  - pytest -v tests --cov web --cov-report xml

after_success:
  - codecov
