name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['2.7', '3.6', '3.7', '3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v2
      - name: Setup python ${{ matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -U pytest pytest-cov pytest-benchmark pygments markdown nbconvert faker jinja2 requests
      - name: Install atom-db
        run: pip install -e ./
      - name: Run tests
        run: pytest -v tests --cov atomdb --cov-report xml
      - name: Coverage
        run: codecov
  check-code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['2.7', '3.6', '3.7', '3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v2
      - name: Setup python ${{ matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -U pytest pytest-cov pytest-benchmark pygments markdown nbconvert faker jinja2 requests
      - name: Run checks
        run: |
            mypy atomdb --ignore-missing-imports
            black atomdb --check --diff
            isort atomdb --check --diff
